### ISSUE TITLE
Fix Minimierung

### ISSUE THREAD

**Issue by timbasel** [hpi-swa-teaching/EPIC-Digitalsimulator#1]
Description:
- Components disappear when you minimize and reopen EPIC. 

Reproducibility:
- Open EPIC
- Minimize EPIC
- Reopen EPIC again

**Comment by citron0xa9** [comment]
auf SystemWindow wird collapseOrExpand aufgerufen, was bei collapse auf das EpicWindow delete aufruft. Bei expand wird dann wieder addMorph gesagt, aber der delete schritt kann nicht rückgängig gemacht werden
