### ISSUE TITLE
Make Components configurable

### ISSUE THREAD

**Issue by timbasel** [hpi-swa-teaching/EPIC-Digitalsimulator#15]
Add support for configurable components. For example let the user switch the orientation of components, add custom names or set the number of pins. This would allow generally improve the user experience because he can (in a way) customize the components to his needs (e.g. have the output pins of a switch on top to prevent unnecessary wiring).

**Comment by timbasel** [comment]
- color components
- color input-/output ports
- switch input-/output port direction
- custom label

**Comment by ekrebs5** [comment]
- i/o delay duration
