### ISSUE TITLE
Fix Help / About Menu

### ISSUE THREAD

**Issue by timbasel** [hpi-swa-teaching/EPIC-Digitalsimulator#3]
Description: 
- Pressing the Help / About Button raises a MessageNotUnderstood Exception.

Reproducibility:
- Open EPIC
- Click on the Help Menu, then About

**Comment by blblblu** [comment]
A simple about window (that currently only shows licensing information) has been added.

![screenshot from 2016-05-06 02-03-25](https://cloud.githubusercontent.com/assets/1103052/15060875/2e30e7c6-132f-11e6-96f3-b7366ae6d198.png)
