### ISSUE TITLE
Fix XML Output

### ISSUE THREAD

**Issue by timbasel** [hpi-swa-teaching/EPIC-Digitalsimulator#4]
Description:
- Pressing the XML / Print XML Button raises a MessageNotUnderstood Exception.

**Comment by blblblu** [comment]
XML output will now be shown within a pop-up window.

![screenshot from 2016-05-09 00-57-49](https://cloud.githubusercontent.com/assets/1103052/15100931/7234eaf4-1581-11e6-9117-c1e1e2b0d8a0.png)
